In [7]:
smash = ['Mario', 'DK', 'Link', 'Samus', 'Yoshi', 'Kirby', 'Fox', 'Pikachu']
smash

['Mario', 'DK', 'Link', 'Samus', 'Yoshi', 'Kirby', 'Fox', 'Pikachu']

In [8]:
smash.append('Luigi')
smash.append('Ness')
smash.append('C. Falcon')
smash.append('Jigglypuff')
smash

['Mario',
 'DK',
 'Link',
 'Samus',
 'Yoshi',
 'Kirby',
 'Fox',
 'Pikachu',
 'Luigi',
 'Ness',
 'C. Falcon',
 'Jigglypuff']

In [9]:
smash.append(['Metal Mario', 'Polygon Team', 'Master Hand'])
smash

['Mario',
 'DK',
 'Link',
 'Samus',
 'Yoshi',
 'Kirby',
 'Fox',
 'Pikachu',
 'Luigi',
 'Ness',
 'C. Falcon',
 'Jigglypuff',
 ['Metal Mario', 'Polygon Team', 'Master Hand']]

In [10]:
smash = ['Original roster'] + smash[8:]
smash

['Original roster',
 'Luigi',
 'Ness',
 'C. Falcon',
 'Jigglypuff',
 ['Metal Mario', 'Polygon Team', 'Master Hand']]

In [11]:
def null_matrix(n, m):
    return [[0] * m for _ in range(n)]
null_matrix(4,4)


[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]

In [12]:
mat = []
for i in range(4):
    mat.append([])
    for i in range(3):
        mat[-1].append(['?'] * 2)
        
mat

[[['?', '?'], ['?', '?'], ['?', '?']],
 [['?', '?'], ['?', '?'], ['?', '?']],
 [['?', '?'], ['?', '?'], ['?', '?']],
 [['?', '?'], ['?', '?'], ['?', '?']]]

In [13]:
mensualidad = {'Disney+': 7, 'Netflix': 8.99, 'Prime': 12.99}
mensualidad

{'Disney+': 7, 'Netflix': 8.99, 'Prime': 12.99}

In [14]:
del mensualidad['Disney+']
mensualidad['Netflix'] = 139
mensualidad['Prime'] = 99
mensualidad['Blim'] = 109
mensualidad

{'Netflix': 139, 'Prime': 99, 'Blim': 109}

In [15]:
mensualidad['Tec'] = 20400
mensualidad

{'Netflix': 139, 'Prime': 99, 'Blim': 109, 'Tec': 20400}

In [16]:
import numpy as np
raw = np.array(list(range(1,17))).reshape((4,4))
raw

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [18]:
raw[0:2, 1:3]

array([[2, 3],
       [6, 7]])

In [19]:
raw[1:4, 2:4]

array([[ 7,  8],
       [11, 12],
       [15, 16]])

In [24]:
label = raw[:, 3]
features = raw[0:4, 0:3]
features


array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [25]:
label

array([ 4,  8, 12, 16])

In [26]:
data = list(zip(features, label))
data

[(array([1, 2, 3]), 4),
 (array([5, 6, 7]), 8),
 (array([ 9, 10, 11]), 12),
 (array([13, 14, 15]), 16)]

In [27]:
size = len(data)
test = data[:int((25*size)/100)]
train = data[int((25*size)/100):size]
print(test)
print(train)

[(array([1, 2, 3]), 4)]
[(array([5, 6, 7]), 8), (array([ 9, 10, 11]), 12), (array([13, 14, 15]), 16)]


In [28]:
# 16) Al 70% de tus amigos les gusta jugar Smash Bros Ultimate, el 35% de tus amigos les gusta jugar
# Smash Bros y Zelda BotW. ¿Cuál es la probabilidad de que a uno de tus amigos le guste jugar Zelda,
#dado que también le gusta jugar Smash? Marca tu respuesta como un comentario en tu código
# de Python.

# La probabilidad es de 50%, ya que 35% de esos 70% que juegan smash, es igual a la mitad de ellos.

In [29]:
# 17) Los resultados de un laboratorio médico indican que fuiste contagiado por una enfermedad
# extremadamente rara y mortal, la prueba tiene un 99% de precisión, por lo que la cantidad de
# falsos positivos que arroja es del 1%. Sabiendo que la enfermedad sólo afecta al 0.1% de la
# población, cuál es la probabilidad de estar enfermo dado que la prueba salió positiva. Marca tu
# respuesta como un comentario en tu código de Python.

# La probabilidad de estar enfermo es del 99%.

In [30]:
# 18) 3x^2cos(x^2) − 2x^4sin(x^2)

In [31]:
# 19) x(2sin(x) + xcos(x) + 4x^2)

In [ ]:
# 20) x: 3x^2 + 2zx + z^2
#     z: 3z^2 + 2xz + x^2